[package]
name = "codetester"
version = "0.1.0"
edition = "2021"
authors = ["AnakinAli"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
serde_json = "1.0"
serde_derive="1.0"
serde="1.0"